"""
Viking Helmet STL Generator
Produces viking_helmet.stl using only numpy + struct (no mesh libs needed).
"""

import struct
import numpy as np

# ── Dimensions (mm) ──────────────────────────────────────────────────────────
R          = 100.0   # Outer dome radius
CUT_Z      = -18.0   # Cut plane (below equator)
RIM_OUT    =   8.0   # Rim protrusion beyond dome edge
RIM_H      =  10.0   # Rim vertical height
NOSE_W     =  20.0   # Nose guard top width
NOSE_H     =  68.0   # Nose guard length
NOSE_T     =   5.0   # Nose guard depth
RIVET_R    =   4.0   # Rivet hemisphere radius
N_RIVETS   =  16     # Rivets around rim
RUNE_RAISE =   2.8   # Rune relief height
RUNE_SW    =   2.0   # Rune stroke width

NT = 72   # theta segments (azimuthal)
NP = 36   # phi segments (polar)


# ── Coordinate helpers ────────────────────────────────────────────────────────
def sph(r, phi, theta):
    """Spherical → cartesian.  phi=0 at north pole, theta=0 along +x."""
    return np.array([
        r * np.sin(phi) * np.cos(theta),
        r * np.sin(phi) * np.sin(theta),
        r * np.cos(phi),
    ])


def tri_normal(a, b, c):
    n = np.cross(b - a, c - a)
    l = np.linalg.norm(n)
    return n / l if l > 1e-12 else n


def quad(a, b, c, d):
    """Quad → 2 triangles (CCW winding = outward)."""
    return [(a, b, c), (a, c, d)]


# ── STL writer ────────────────────────────────────────────────────────────────
def write_stl_binary(path, tris):
    """Write list of (v0, v1, v2) numpy float32 triangles as binary STL."""
    msg = b"Viking Helmet - generated by generate_helmet.py"
    header = msg + b" " * (80 - len(msg))
    with open(path, "wb") as f:
        f.write(header)
        f.write(struct.pack("<I", len(tris)))
        for t in tris:
            a, b, c = (np.asarray(v, dtype=np.float32) for v in t)
            n = tri_normal(a, b, c).astype(np.float32)
            f.write(struct.pack("<3f", *n))
            f.write(struct.pack("<3f", *a))
            f.write(struct.pack("<3f", *b))
            f.write(struct.pack("<3f", *c))
            f.write(struct.pack("<H", 0))   # attribute byte count
    print(f"Written {len(tris):,} triangles → {path}")


# ── Part 1: Dome ──────────────────────────────────────────────────────────────
def make_dome():
    tris = []
    phi_max = np.arccos(CUT_Z / R)   # angle where sphere meets cut plane
    thetas = np.linspace(0, 2 * np.pi, NT, endpoint=False)
    phis   = np.linspace(0, phi_max, NP + 1)

    # Apex fan (top)
    apex = sph(R, 0, 0)
    for i, t in enumerate(thetas):
        a = sph(R, phis[1], t)
        b = sph(R, phis[1], thetas[(i + 1) % NT])
        tris.append((apex, a, b))

    # Quad rings
    for j in range(1, NP):
        for i, t in enumerate(thetas):
            t_next = thetas[(i + 1) % NT]
            a = sph(R, phis[j],     t)
            b = sph(R, phis[j],     t_next)
            c = sph(R, phis[j + 1], t_next)
            d = sph(R, phis[j + 1], t)
            tris.extend(quad(a, b, c, d))

    return tris


# ── Part 2: Rim ───────────────────────────────────────────────────────────────
def make_rim():
    tris = []
    r_inner = np.sqrt(R**2 - CUT_Z**2)
    r_outer = r_inner + RIM_OUT
    z_top   = CUT_Z
    z_bot   = CUT_Z - RIM_H
    thetas  = np.linspace(0, 2 * np.pi, NT, endpoint=False)

    for i, t in enumerate(thetas):
        t2 = thetas[(i + 1) % NT]
        ct,  st  = np.cos(t),  np.sin(t)
        ct2, st2 = np.cos(t2), np.sin(t2)

        # Corners
        oi  = np.array([r_outer * ct,  r_outer * st,  z_top])
        oi2 = np.array([r_outer * ct2, r_outer * st2, z_top])
        ii  = np.array([r_inner * ct,  r_inner * st,  z_top])
        ii2 = np.array([r_inner * ct2, r_inner * st2, z_top])
        ob  = np.array([r_outer * ct,  r_outer * st,  z_bot])
        ob2 = np.array([r_outer * ct2, r_outer * st2, z_bot])
        ib  = np.array([r_inner * ct,  r_inner * st,  z_bot])
        ib2 = np.array([r_inner * ct2, r_inner * st2, z_bot])

        # Top face (outward = +z)
        tris.extend(quad(ii, ii2, oi2, oi))
        # Bottom face (outward = −z)
        tris.extend(quad(ob, ob2, ib2, ib))
        # Outer wall (outward = +r)
        tris.extend(quad(ob, oi, oi2, ob2))
        # Inner wall (outward = −r)
        tris.extend(quad(ib2, ii2, ii, ib))

    return tris


# ── Part 3: Rivets ────────────────────────────────────────────────────────────
def make_rivets():
    tris = []
    r_inner = np.sqrt(R**2 - CUT_Z**2)
    r_mid   = r_inner + RIM_OUT / 2.0
    z_base  = CUT_Z           # sit on top face of rim

    nr  = 8   # rivet phi segments
    nrt = 16  # rivet theta segments
    phis_r   = np.linspace(0, np.pi / 2, nr + 1)
    thetas_r = np.linspace(0, 2 * np.pi, nrt, endpoint=False)

    for k in range(N_RIVETS):
        angle = 2 * np.pi * k / N_RIVETS
        cx = r_mid * np.cos(angle)
        cy = r_mid * np.sin(angle)
        cz = z_base

        def rv(phi, theta):
            return np.array([
                cx + RIVET_R * np.sin(phi) * np.cos(theta),
                cy + RIVET_R * np.sin(phi) * np.sin(theta),
                cz + RIVET_R * np.cos(phi),
            ])

        # Apex fan
        apex = np.array([cx, cy, cz + RIVET_R])
        for i, t in enumerate(thetas_r):
            a = rv(phis_r[1], t)
            b = rv(phis_r[1], thetas_r[(i + 1) % nrt])
            tris.append((apex, a, b))

        # Quad rings
        for j in range(1, nr):
            for i, t in enumerate(thetas_r):
                t2 = thetas_r[(i + 1) % nrt]
                a = rv(phis_r[j],     t)
                b = rv(phis_r[j],     t2)
                c = rv(phis_r[j + 1], t2)
                d = rv(phis_r[j + 1], t)
                tris.extend(quad(a, b, c, d))

        # Base disk cap (fills the flat circle at z=z_base)
        center_base = np.array([cx, cy, cz])
        for i, t in enumerate(thetas_r):
            t2 = thetas_r[(i + 1) % nrt]
            a = rv(np.pi / 2, t)
            b = rv(np.pi / 2, t2)
            # Wind inward so normal faces −z
            tris.append((center_base, b, a))

    return tris


# ── Part 4: Nose guard ────────────────────────────────────────────────────────
def make_nose_guard():
    tris = []
    N_STEPS = 20
    z_top = CUT_Z - RIM_H
    z_bot = CUT_Z - RIM_H - NOSE_H
    r_inner = np.sqrt(R**2 - CUT_Z**2)

    zs = np.linspace(z_top, z_bot, N_STEPS + 1)
    ts = np.linspace(0.0, 1.0, N_STEPS + 1)

    def half_w(t):
        return (NOSE_W / 2.0) * (1.0 - 0.75 * t)   # taper to 25%

    def x_front(t):
        # Front face starts just outside dome at the top
        return r_inner + NOSE_T * (1.0 - 0.5 * t)

    # Build quad strips for each face
    for i in range(N_STEPS):
        hw0  = half_w(ts[i]);     hw1  = half_w(ts[i + 1])
        xf0  = x_front(ts[i]);    xf1  = x_front(ts[i + 1])
        xb0  = xf0 - NOSE_T;      xb1  = xf1 - NOSE_T
        z0   = zs[i];             z1   = zs[i + 1]

        # Front face (+x direction)
        fl0  = np.array([xf0, -hw0, z0])
        fr0  = np.array([xf0,  hw0, z0])
        fl1  = np.array([xf1, -hw1, z1])
        fr1  = np.array([xf1,  hw1, z1])
        tris.extend(quad(fl0, fr0, fr1, fl1))

        # Back face (−x)
        bl0  = np.array([xb0, -hw0, z0])
        br0  = np.array([xb0,  hw0, z0])
        bl1  = np.array([xb1, -hw1, z1])
        br1  = np.array([xb1,  hw1, z1])
        tris.extend(quad(br0, bl0, bl1, br1))

        # Left face (−y)
        tris.extend(quad(fl0, fl1, bl1, bl0))

        # Right face (+y)
        tris.extend(quad(fr1, fr0, br0, br1))

    # Top cap
    hw  = half_w(0.0);  xf = x_front(0.0);  xb = xf - NOSE_T
    tfl = np.array([xf, -hw, z_top]); tfr = np.array([xf,  hw, z_top])
    tbl = np.array([xb, -hw, z_top]); tbr = np.array([xb,  hw, z_top])
    tris.extend(quad(tfl, tbl, tbr, tfr))

    # Bottom cap
    hw  = half_w(1.0);  xf = x_front(1.0);  xb = xf - NOSE_T
    bfl = np.array([xf, -hw, z_bot]); bfr = np.array([xf,  hw, z_bot])
    bbl = np.array([xb, -hw, z_bot]); bbr = np.array([xb,  hw, z_bot])
    tris.extend(quad(bfr, bbl, bbl, bbr))   # degenerate—replace with proper
    tris.pop()
    tris.extend(quad(bfr, bfl, bbl, bbr))

    return tris


# ── Part 5: Runes ─────────────────────────────────────────────────────────────

# Each rune = list of stroke segments in normalised [0,1]² space
# Coordinates: (x0,y0, x1,y1)  x=right, y=up within the rune glyph cell
RUNES = {
    "fehu":     [(0,.1,.2,.9),(.2,.9,.5,.5),(.2,.5,.5,.9)],
    "uruz":     [(0,.1,0,.9),(.0,.9,.4,.5),(.4,.5,.4,.1)],
    "thurisaz": [(0,.5,1,.5),(.5,.1,.5,.9),(.0,.9,.5,.5)],
    "ansuz":    [(0,.1,0,.9),(.4,.1,.4,.9),(.0,.7,.4,.4)],
    "gebo":     [(0,.1,1,.9),(1,.1,0,.9)],
    "raido":    [(0,.1,0,.9),(.0,.9,.4,.6),(.4,.6,.2,.1),(.0,.5,.4,.5)],
    "wunjo":    [(0,.9,.5,.3),(0,.1,.5,.5),(.5,.3,.5,.9)],
    "tiwaz":    [(.5,.1,.5,.9),(0,.5,.5,.9),(1,.5,.5,.9)],
}

RUNE_PLACEMENTS = [
    ("fehu",     np.radians( 40), np.radians(42)),
    ("uruz",     np.radians(130), np.radians(42)),
    ("thurisaz", np.radians(220), np.radians(42)),
    ("ansuz",    np.radians(310), np.radians(42)),
    ("gebo",     np.radians( 90), np.radians(28)),
    ("raido",    np.radians(270), np.radians(28)),
    ("wunjo",    np.radians(180), np.radians(35)),
    ("tiwaz",    np.radians(  0), np.radians(28)),
]

RUNE_SIZE = 18.0   # glyph cell size in mm


def stroke_box(p0, p1, normal, sw, sh):
    """
    Raise a rectangular prism along the stroke p0→p1 on the surface.
    normal  – outward surface normal at the stroke location
    sw      – stroke width (half = sw/2 perpendicular to stroke direction)
    sh      – stroke height (raise above surface)
    """
    tris = []
    d = p1 - p0
    length = np.linalg.norm(d)
    if length < 1e-6:
        return tris
    along = d / length
    side  = np.cross(along, normal)
    side /= max(np.linalg.norm(side), 1e-12)
    half  = sw / 2.0

    # 4 corner base points (on surface)
    b00 = p0 - side * half
    b01 = p0 + side * half
    b10 = p1 - side * half
    b11 = p1 + side * half

    # 4 corner top points (raised)
    n_sh = normal * sh
    t00 = b00 + n_sh
    t01 = b01 + n_sh
    t10 = b10 + n_sh
    t11 = b11 + n_sh

    # Top face
    tris.extend(quad(t00, t10, t11, t01))
    # Front (p0 end)
    tris.extend(quad(b01, b00, t00, t01))
    # Back (p1 end)
    tris.extend(quad(b10, b11, t11, t10))
    # Left side
    tris.extend(quad(b00, b10, t10, t00))
    # Right side
    tris.extend(quad(b11, b01, t01, t11))

    return tris


def make_runes():
    tris = []

    for name, theta, phi in RUNE_PLACEMENTS:
        # Surface point and local frame
        center  = sph(R, phi, theta)
        normal  = center / np.linalg.norm(center)

        # "right" = along +theta direction on surface
        right = np.array([-np.sin(theta), np.cos(theta), 0.0])
        if np.linalg.norm(right) < 1e-6:
            right = np.array([1.0, 0.0, 0.0])
        right = right - np.dot(right, normal) * normal
        right /= max(np.linalg.norm(right), 1e-12)

        # "up" = cross(normal, right) tangent pointing toward pole
        up = np.cross(normal, right)
        up /= max(np.linalg.norm(up), 1e-12)

        def cell_point(nx, ny):
            """Normalised [0,1]² glyph coord → 3-D surface point."""
            ox = (nx - 0.5) * RUNE_SIZE
            oy = (ny - 0.5) * RUNE_SIZE
            return center + right * ox + up * oy

        strokes = RUNES[name]
        for (x0, y0, x1, y1) in strokes:
            p0 = cell_point(x0, y0)
            p1 = cell_point(x1, y1)
            tris.extend(stroke_box(p0, p1, normal, RUNE_SW, RUNE_RAISE))

    return tris


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    print("Building dome …")
    all_tris = make_dome()

    print("Building rim …")
    all_tris += make_rim()

    print("Building rivets …")
    all_tris += make_rivets()

    print("Building nose guard …")
    all_tris += make_nose_guard()

    print("Building runes …")
    all_tris += make_runes()

    out = "/home/torarne/førstetest/viking_helmet.stl"
    write_stl_binary(out, all_tris)
    size_mb = len(all_tris) * 50 / 1e6
    print(f"Estimated binary size: ~{size_mb:.1f} MB")
    print("Done!  View in MeshLab, Blender, PrusaSlicer, or Windows 3D Viewer.")


if __name__ == "__main__":
    main()
